### PR TITLE
Add parent method

### PR DESCRIPTION
**Pull request by kevingilpin**
Implements parent method along with documentation and tests. Parent method returns the parent node(s) of the node(s) it is called upon.

I followed the Enzyme behavior, rather than the Umbrella behavior, as a personal preference of simplicity, versus duplicating the filter behavior within this method.

ie. .parent().filter('li') versus .parent('li')

But, I can easily add the filter behavior to this method if you feel differently.

### CODE REVIEW

**Review by franciscop — APPROVED** [review]
Again great work! I'd add an example or two actually running a test, not just using the selector, like:

```js
expect($("...").parent().length).toBe(2);
```

But it already looks great, approved!

**Comment by kevingilpin** [comment]
Thanks, Francisco! 

I have a couple of the following tests in the tests file, are these what you were looking for? 

The $ values don't have a .length property so I had to check the nodes property on them specifically.
`
expect($list.find('a').parent().nodes).toHaveLength(2);
  `

**Comment by franciscop** [comment]
Oh sorry I mean examples of a full test running in the documentation, not just in the test files.

**Comment by franciscop** [comment]
Like, the docs show how to select a node, but it'd be nice if they also showed an example of a full test run and not just the selector itself.

**Comment by kevingilpin** [comment]
Hey Francisco, let me know if the changes I added to the doc are what you were thinking.

**Comment by franciscop** [comment]
Awesome, thanks!

**Comment by franciscop** [comment]
Yes, that's exactly what I was thinking about!

**Pull request merged**
