### PR TITLE
Removed non-string check part

### PR DESCRIPTION
**Pull request by vitalysmnv**
provided 100% coverage.

### CODE REVIEW

**Review by vitalysmnv — COMMENTED** [review]
Reviewed!

**Comment by franciscop** [comment]
Sorry but what's the improvement here? We want to always receive a string, right?

**Comment by vitalysmnv** [comment]
I want to provide 100% statement coverage for that file.

**Comment by vitalysmnv** [comment]
Next time I will provide 100% coverage by updating test.js.

**Comment by vitalysmnv** [comment]
I'm closing this request. Try with other method to improve code coverage.

**Pull request closed without merging**
